### ISSUE TITLE
conflicts with BetterSearch /error when click "browse"

### ISSUE THREAD

**Issue by freemedom** [ijgnd/anki__browser_side_by_side__horizontal_split#6]
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-13 21:23:37

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "aqt\toolbar.py", line 169, in _linkHandler
  File "aqt\toolbar.py", line 187, in _browseLinkHandler
  File "aqt\main.py", line 1067, in onBrowse
  File "aqt\__init__.py", line 101, in open
TypeError: __init__() got an unexpected keyword argument 'card'

only enable this addon

**Comment by freemedom** [comment]
https://forums.ankiweb.net/t/browser-table-editor-side-by-side-horizontal-split-official-thread/548/10

i solved this problem by this

**Comment by ijgnd** [comment]
Have you also seen their next post at, https://forums.ankiweb.net/t/browser-table-editor-side-by-side-horizontal-split-official-thread/548/12 ?

Does it work after reinstalling BetterSearch and restarting Anki? Or do you get the problem again?
